In [124]:
import pandas as pd
import numpy as np

In [125]:

# Method chaining begins
def load_and_process(url):
    df = (
        data
        .drop(columns=['Positive affect', 'Negative affect'])
        .loc[lambda x: x['year']>2015]
        .sort_values("Life Ladder", ascending=False)
        .dropna(axis='rows', thresh =8).reset_index(drop=True)
        .reset_index(drop=True)
    
    )

    return df

In [126]:
data = pd.read_csv('/Users/Khalidmahmoud/Desktop/DATA301/project-group61-project/data/raw/world-happiness-report.csv') # this a data file that gets loaded
load_and_process(data)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,2020,7.889,10.750,0.962,72.1,0.962,-0.116,0.164
1,Finland,2018,7.858,10.783,0.962,71.9,0.938,-0.127,0.199
2,Finland,2017,7.788,10.768,0.964,71.8,0.962,-0.002,0.192
3,Finland,2019,7.780,10.792,0.937,72.0,0.948,-0.052,0.195
4,Switzerland,2019,7.694,11.136,0.949,74.4,0.913,0.036,0.294
...,...,...,...,...,...,...,...,...,...
639,Afghanistan,2018,2.694,7.692,0.508,52.6,0.374,-0.094,0.928
640,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831
641,Central African Republic,2016,2.693,6.785,0.290,44.9,0.624,0.033,0.859
642,Afghanistan,2017,2.662,7.697,0.491,52.8,0.427,-0.121,0.954
643,Afghanistan,2019,2.375,7.697,0.420,52.4,0.394,-0.108,0.924

In [6]:
temp = {'Fruits': ["apple", "banana", "grapefruit"], 'Mass (g)': [50,30,45]}

In [7]:
pd.DataFrame.from_dict(temp)

       Fruits  Mass (g)
0       apple        50
1      banana        30
2  grapefruit        45